on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

  pull_request:  # Trigger on PR creation, updates, and reopen events
    types: [opened, synchronize, reopened]

jobs:
  validate-file:
    runs-on: ubuntu-latest
    environment: development

    steps: 
      - name: Generate map via PM action
        # You may pin to the exact commit or the version.
        # uses: JuanQuGo/product-map-action@e11422d93a9f689161850adb3efb220a04b12026
        uses: JuanQuinGom/productmap-requirement-analyzer-action@0.0.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'main'
